### PR TITLE
Changed it so the images are all loaded at the beginning. I also found a

### PR DESCRIPTION
**Pull request by sstone93**
way to only update the chit images if they are newly discovered. And I
added the hover overs so you can see the underlying tile.

### CODE REVIEW

**Comment by SunsetBlade** [comment]
Awesome! I just tested it and it is back to being super smooth, great work.

On Sun, Apr 5, 2015 at 6:01 PM, sstone93 notifications@github.com wrote:

> Merged #117 https://github.com/sstone93/MAGIC/pull/117.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sstone93/MAGIC/pull/117#event-273747487.

## 

Nicholas Laws

**Comment by sstone93** [comment]
Thanks.
I'm going to try to look into making the textAreas scrollable next and maybe the issue where someone else moving resets your comboboxes.

**Comment by SunsetBlade** [comment]
for the combo boxes, I was thinking about stroign your currently selected
value and then if it still exists after the update is done, reselecting it?
that way you would only lose your selection if the action you were on is no
longer valid,

On Sun, Apr 5, 2015 at 6:09 PM, sstone93 notifications@github.com wrote:

> Thanks.
> I'm going to try to look into making the textAreas scrollable next and
> maybe the issue where someone else moving resets your comboboxes.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sstone93/MAGIC/pull/117#issuecomment-89863189.

## 

Nicholas Laws

**Comment by sstone93** [comment]
That might work, I was thinking of just separating the updating or that panel and limiting it to when it is actually necessary.

**Pull request merged**
