### PR TITLE
some changes after testing

### PR DESCRIPTION
**Pull request by ChantalForget**

### CODE REVIEW

**Comment by ChantalForget** [comment]
@SunsetBlade do you have a way to get the board tiles? I'm trying to set the characters initial starting location, and I'm not sure how to do that without creating a new tile

**Comment by SunsetBlade** [comment]
For now, just leave their starting location as either a GarrisonName enum
or whatever it is right now (since all characters start at the inn which is
a garrison).
I will set it up so that when the board is initialized, you give the
constructor an array of characters to place and it will handle setting the
location of the character instances.

On Fri, Feb 20, 2015 at 1:49 PM, ChantalForget notifications@github.com
wrote:

> @SunsetBlade https://github.com/SunsetBlade do you have a way to get
> the board tiles? I'm trying to set the characters initial starting
> location, and I'm not sure how to do that without creating a new tile
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sstone93/MAGIC/pull/30#issuecomment-75296704.

## 

Nicholas Laws

**Comment by ChantalForget** [comment]
ok, sounds good!
for clarifying though, the characters just have a startingLocation, it's the players that need the location (when the game starts, I was just trying to grab the characters startingLocation and set it as the players current location). 
Just so you have an idea of what's happening when you set up the board initialization :)

**Comment by SunsetBlade** [comment]
good catch, I has just assumed that current location was a character thing
but yeah, having it in player makes way more sense lol

On Fri, Feb 20, 2015 at 3:03 PM, ChantalForget notifications@github.com
wrote:

> ok, sounds good!
> for clarifying though, the characters just have a startingLocation, it's
> the players that need the location (an which when the game starts, I was
> just trying to grab the characters startingLocation and set it as the
> players current location).
> Just so you have an idea of what's happening when you set up the board
> initialization :)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sstone93/MAGIC/pull/30#issuecomment-75309359.

## 

Nicholas Laws

**Pull request merged**
