### PR TITLE
character, weapon, armour, dice models

### PR DESCRIPTION
**Pull request by ChantalForget**
@michaelcatt 

given that in JP's email he said he wanted some of the dwellings to be able to be placed at random, I'm thinking we should have a dwelling model.. what do you think?

Also since the dice class basically will just have roll ( I can't really think of what else it would need.. should we just put it in a utils class instead, where we could add in functionality like that?) 

Also in terms of the `ranged` boolean in the armour class, that's for whether or not a weapon is alerted right? Or is that for something else :p

### CODE REVIEW

**Comment by ChantalForget** [comment]
weapon and armor requirements in #4 
also have i been misspelling armour? is it armor?

**Comment by lemmingllama** [comment]
Armour is the Canadian spelling. Both are technically correct

**Comment by lemmingllama** [comment]
What would dwellings have then? They would just need a picture and a location, right?

Dice class could definitely become part of a utility class. It makes more sense overall.

As for ranged, some weapons are ranged weapons (like bows and stuff). I don't know if that really matters a lot or not, but I believe there were some advantages and disadvantages of range.

**Comment by ChantalForget** [comment]
Yeah, I can't really think of what else they would need. 
Alright, I'll create a different PR after this one is merged in to put the dice functionality in a utils class instead.

**Pull request merged**
