### PR TITLE
armour model changes

### PR DESCRIPTION
**Pull request by ChantalForget**
@michaelcatt not sure what you think about taking out health
also, for weight, since i'm fairly certain that weight for both weapon and armour will be LIGHT, MEDIUM or HEAVY, that we should just rename the enum to Weight or something so we can use it for both armour and weapons
(`ArmourWeaponWeight` maybe?)

### CODE REVIEW

**Comment by lemmingllama** [comment]
It would probably be easier to just use one enum. Something like "itemweight". Although characters also have the same weight categories, which determines how much they can carry

**Comment by lemmingllama** [comment]
I do think that we are supposed to assume that inventories are infinitely large for this iteration though.

**Comment by ChantalForget** [comment]
haha thanks, for the life of me I couldn't think of a good name. I'll change that once I have the weight and armour PR's merged in

**Comment by ChantalForget** [comment]
I think for the weight categories it depends on the move chit. When I was reading the rules, it sounded like a character could hold any number of items while in a clearing, but when they moved to another one, they had to play a move chit to move their belongings (the ones that didn't have negligible values). So, if they played a MEDIUM move chit or whatever, only the medium (and light) items could be moved, but the heavy ones remained in the clearing they left

**Pull request merged**
