### PR TITLE
fixing some of combat code

### PR DESCRIPTION
**Pull request by ChantalForget**

### CODE REVIEW

**Comment by ChantalForget** [comment]
@michaelcatt do you mind going through your combat code? There's still some more mistakes when I open it in eclipse

**Comment by lemmingllama** [comment]
@ChantalForget What mistakes are you getting? I'm not currently seeing any on my end

**Comment by lemmingllama** [comment]
@ChantalForget  Ok, I found the problem. Apparently running code through EGit entirely removes some error handling. I'll have it cleaned up soon.

**Comment by ChantalForget** [comment]
haha omg egit _shakes head_

**Pull request merged**
